services:
  backend:
    build:
      context: ./crew_backend
      dockerfile: Dockerfile
    environment:
      APP_ENV: ${APP_ENV:-prod}
    volumes:
      - type: bind
        source: ./crew_backend/data
        target: /app/data
    ports:
      - "127.0.0.1:8000:8000"
    command: /start.sh
