"""Add username column

Revision ID: 10d6e8ac68f7
Revises: 088081e1a4bb
Create Date: 2022-01-02 17:34:08.832475

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "10d6e8ac68f7"
down_revision = "088081e1a4bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("username", sa.String(), nullable=True))
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_column("user", "username")
    # ### end Alembic commands ###
